### PR TITLE
Fix bug trajectory

### LINKED ISSUE #20: 'normalize_to_start_year' should use the start year of 'projected'
It can happen that the benchmark data are available for years prior to start year of 'projected' - this results in a bug right now.

The data should be filtered according to start year of 'projected' rows in the input data.

### PR DESCRIPTION
**Pull request by MonikaFu**
Closes #20 

In this PR I add a filter that ensures that the trajectory chart data start year is the start year of 'projected'.

### CODE REVIEW

File: R/prepare_for_trajectory_chart.R [hunk 1]
```diff
@@ -38,11 +38,17 @@ prepare_for_trajectory_chart <- function(data_preprocessed,
                                          value_name,
                                          end_year_filter = 2025,
                                          normalize_to_start_year = TRUE) {
+
+  year_start_projected <- min(data_preprocessed %>%
+                    filter(.data$metric == 'projected') %>%
+                      pull(.data$year))
```
Comment (maurolepore) [inline R/prepare_for_trajectory_chart.R:44]: Nit: I find that piping inside a function call is a bit hard to read because I'm not used to it. Here it caused a weird alignment with the rest of the code.

File: R/prepare_for_trajectory_chart.R [hunk 2]
```diff
@@ -38,11 +38,17 @@ prepare_for_trajectory_chart <- function(data_preprocessed,
...
+
   data_filtered <- data_preprocessed %>%
     filter(.data$sector == !!sector_filter) %>%
```
Comment (maurolepore) [inline R/prepare_for_trajectory_chart.R:47]: Here `!!` seems unnecessary:

``` r
library(rlang)

f1 <- function(spp) {
  # Good
  dplyr::filter(iris,.data$Species == spp)
}

f2 <- function(spp) {
  # Bad
  dplyr::filter(iris,.data$Species == !! spp)
}

identical(f1("setosa"), f2("setosa"))
#> [1] TRUE
```

<sup>Created on 2021-04-06 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

File: tests/testthat/test-prepare_for_trajectory_chart.R [hunk 3]
```diff
@@ -199,3 +199,22 @@ test_that("with input missing crucial columns errors ungracefully", {
     ungraceful_message
   )
 })
+
+test_that("outputs data with year starting at earliest at the start of 'projected'", {
```
Comment (maurolepore) [inline tests/testthat/test-prepare_for_trajectory_chart.R:203]: The test seems great but the use of "at" in the test title is a bit confusing. Did you mean to use "[as] early [as] the start of 'projected'"?

**Review by maurolepore — APPROVED** [review]
I thinks the use of `!!` is unnecessary but I suspect there is a reason for it so I approve but please check.

File: R/prepare_for_trajectory_chart.R (hunk 2 above)
Comment (cjyetman) [reply R/prepare_for_trajectory_chart.R:47]: I think using `!!` is good practice to avoid collisions with existing column names in the data frame, otherwise tidyselect has to choose for you since it would be ambiguous...
``` r
library(dplyr)

f1 <- function(Sepal.Length) {
  as_tibble(dplyr::filter(iris, .data$Species == Sepal.Length))
}

f2 <- function(Sepal.Length) {
  as_tibble(dplyr::filter(iris,.data$Species == !! Sepal.Length))
}

f1("setosa")
#> # A tibble: 0 x 5
#> # … with 5 variables: Sepal.Length <dbl>, Sepal.Width <dbl>,
#> #   Petal.Length <dbl>, Petal.Width <dbl>, Species <fct>
f2("setosa")
#> # A tibble: 50 x 5
#>    Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#>           <dbl>       <dbl>        <dbl>       <dbl> <fct>  
#>  1          5.1         3.5          1.4         0.2 setosa 
#>  2          4.9         3            1.4         0.2 setosa 
#>  3          4.7         3.2          1.3         0.2 setosa 
#>  4          4.6         3.1          1.5         0.2 setosa 
#>  5          5           3.6          1.4         0.2 setosa 
#>  6          5.4         3.9          1.7         0.4 setosa 
#>  7          4.6         3.4          1.4         0.3 setosa 
#>  8          5           3.4          1.5         0.2 setosa 
#>  9          4.4         2.9          1.4         0.2 setosa 
#> 10          4.9         3.1          1.5         0.1 setosa 
#> # … with 40 more rows
```

File: R/prepare_for_trajectory_chart.R (hunk 1 above)
Comment (cjyetman) [reply R/prepare_for_trajectory_chart.R:44]: you could put `min` at the end of the pipe...
```r
year_start_projected <- data_preprocessed %>% filter(.data$metric == 'projected') %>% pull(.data$year) %>% min()
```

File: R/prepare_for_trajectory_chart.R (hunk 2 above)
Comment (cjyetman) [reply R/prepare_for_trajectory_chart.R:47]: and speaking of which... I just found a bug in the SDA code in PACTA_analysis for exactly this reason... a function argument that has the same name as a column in the data frame is used inside a pipe chain and tidyselect defaults to the column in the data frame... imagine...
```r
filter_sector <- function(data, ald_sector) {
  dplyr::filter(data, ald_sector %in% ald_sector)
}

ald_sector <- c("Cement", "Steel", "Aviation")
filter_sector(portfolio, ald_sector)
```

Comment (maurolepore) [reply R/prepare_for_trajectory_chart.R:47]: Thanks @cjyetman. Although here the arguments and columns seem to have different names, this is a good opportunity to remind that the pronoun `.env$` helps disambiguate such name clashes. (But maybe this is not the forum -- sorry Monika)


``` r
# Refer to this data frame colum as `.data$ald_sector`
portfolio <- tibble::tribble(
  ~ald_sector,
  "Cement", 
  "Steel", 
  "Aviation"
)

# Refer to this environmental variable as .env$ald_sector
ald_sector <- "Steel"

# Good: Explicit
# .data$var explicitely look for `var` in the data frame
# .env$var explicitely look for `var` in the environment
filter_sector1 <- function(data, ald_sector) {
  dplyr::filter(data, .data$ald_sector %in% .env$ald_sector)
}

filter_sector1(portfolio, ald_sector)
#> # A tibble: 1 x 1
#>   ald_sector
#>   <chr>     
#> 1 Steel



# Bad: Ambigous
filter_sector2 <- function(data, ald_sector) {
  dplyr::filter(data, ald_sector %in% ald_sector)
}

filter_sector2(portfolio, ald_sector)
#> # A tibble: 3 x 1
#>   ald_sector
#>   <chr>     
#> 1 Cement    
#> 2 Steel     
#> 3 Aviation
```

<sup>Created on 2021-04-06 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

File: tests/testthat/test-prepare_for_trajectory_chart.R (hunk 3 above)
Comment (MonikaFu) [reply tests/testthat/test-prepare_for_trajectory_chart.R:203]: I was struggling with the wording here 😄

File: R/prepare_for_trajectory_chart.R (hunk 2 above)
Comment (MonikaFu) [reply R/prepare_for_trajectory_chart.R:47]: since I've been using `!!` everywhere so far I think that I will stick with it here.

Comment (maurolepore) [reply R/prepare_for_trajectory_chart.R:48]: While my reprex above suggests `!!` causes no error, it does not prove it's neutral in all situations. In my opinion it hurts at least in that it makes the code harder to understand -- as the reader wonders why `!!` is there. You may add a comment explaining why, but it may be better and simpler to just remove `!!`. You may do a bunch at once with something like this (Shift + Control + F):

image
